- name: install memcached
  become: True
  apt:
    name: "{{ item }}" 
    cache_valid_time: "{{ cache_update_valid_secs }}"
  with_items:
    - memcached
    - libmemcached-dev

- name: install pylibmc
  become: True
  pip:
    name: "{{ item }}"
  with_items:
    - pylibmc

- name: restart uwsgi
  become: True
  supervisorctl:
    name: uwsgi
    state: "restarted"


