- name: add codemash hoodie
  django_manage:
    command: codemash
    app_path: "{{ saleor_directory }}"
  environment:
    SECRET_KEY: "{{ django_secret_key }}"

- name: populate extra products
  django_manage:
    command: populatedb
    app_path: "{{ saleor_directory }}"
  environment:
    SECRET_KEY: "{{ django_secret_key }}"

- name: restock to raise quanities
  django_manage:
    command: restock 1000000000
    app_path: "{{ saleor_directory }}"
  environment:
    SECRET_KEY: "{{ django_secret_key }}"
