- name: set ubuntu user password
  become: True
  template:
    src: sshd_config_with_password
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode:  0644

- name: restart ssh daemon
  become: True
  service:
    name: ssh
    state: restarted
