- name: set ubuntu user password
  become: True
  user:
    name: ubuntu
    password: "{{ ubuntu_password }}"

- name: unlock ubuntu in cloud-init
  become: True
  template:
    src: cloud-unlock-ubuntu.cfg
    dest: /etc/cloud/cloud.cfg
    mode: 0644 
